### ISSUE TITLE
New CRAN issue?

### ISSUE THREAD

**Issue by dpavlic** [rticulate/import#19]
Just wondering if the new import functionality will make its way to CRAN? I really like the feature of being able to use R scripts as imports. 

My use case: I am using checkpoint for package management, so the dependence is on CRAN; but precisely because of this dependence, working with the universe _outside_ CRAN (/MRAN) is somewhat frustrating. The solution I've been using is https://github.com/wahani/modules which is perfectly fine, but I like the all in one solution offered by this package.

**Comment by torfason** [comment]
We are working on it. The version master has been updated recently, testing that version, and commenting on any potential regressions is greatly appreciated and helps speed up submission to CRAN. Get it with:
`remotes::install_github("smbache/import")`

[ fixed-in-master : We can close this issue when the CRAN release is out ]

**Comment by torfason** [comment]
This has been released to CRAN. Closed as fixed in release 1.2.0
