### ISSUE TITLE
import function only for a specific environment

### ISSUE THREAD

**Issue by vnijs** [rticulate/import#48]
I expected that in the code below the first and second `count` would reference `dplyr` but the third would show `count` to be part of the `plyr` package. Instead, the second `count` already refers to `plyr`. 

Is my intended/expected import process possible with `import`? 

```
env <- new.env(emptyenv())
attr(env, "name") <- "env"
library(dplyr)
count
import::from(plyr, count, .into = "env")
count
attach(env)
count
```

**Comment by smbache** [comment]
The syntax for importing into the env is
```R
import::from(plyr, count, .into = {env})
```

**Comment by vnijs** [comment]
Nice! Thank you @smbache
