### ISSUE TITLE
Placing to-be-imported operators inside double vs. single quote?

### ISSUE THREAD

**Issue by chunyunma** [rticulate/import#52]
I really like the philosophy behind `import` and introduced it to students in my class. 
Recently, a couple of students mentioned to me that 
when they tried to import the pipe operator `%>%` from `magrittr` package, 
placing the pipe operator inside a pair of single vs. double quotation marks made a difference.
Only `import::from(magrittr, "%>%")` worked for them, 
whereas `import::from(magrittr, '%>%')` did not. 

I could not replicate this problem myself either on a Mac or on a Windows. 
Both single and double quotes worked properly for me. 
I even tried a pair of backticks \` \`, which also worked.
For the record, both students who had trouble with single quotes were on Windows.

I am aware of the [single vs. double quotes subtleties](https://stat.ethz.ch/pipermail/r-help/2010-February/228168.html) 
and that double quotes are the preferred method. 
However, I still want to know whether anyone is aware of such differences for `import` method
and if so, why.

Thank you very much!

**Comment by smbache** [comment]
Thanks for the support of the package.

I cannot replicate the issue, and don't know how that would happen:

```R
> identical(quote("hello"), quote('hello'))
[1] TRUE
```
If you get more information to share, or a stack trace, that would maybe shed some light...

**Comment by chunyunma** [comment]
Thank you very much for the suggestion! 
The student and I tried on their machine again, 
but the error seems unable to reproduce. 
I have asked the students to keep an eye out and save the stack trace if it happens again. 

I will close the issue for now and re-open it if I have more information to share.
Thanks again!
